module.exports = {"array": [
  {"id":"world","name":"World","code":"WORLD"},
  {"id":"albania","name":"Albania","code":"AL"},
  {"id":"argentina","name":"Argentina","code":"AR"},
  {"id":"australia","name":"Australia","code":"AU"},
  {"id":"austria","name":"Austria","code":"AT"},
  {"id":"belarus","name":"Belarus","code":"BY"},
  {"id":"belgium","name":"Belgium","code":"BE"},
  {"id":"bolivia","name":"Bolivia","code":"BO"},
  {"id":"bosnia-and-herzegovina","name":"Bosnia and Herzegovina","code":"BA"},
  {"id":"brazil","name":"Brazil","code":"BR"},
  {"id":"brunei","name":"Brunei","code":"BN"},
  {"id":"bulgaria","name":"Bulgaria","code":"BG"},
  {"id":"cameroon","name":"Cameroon","code":"CM"},
  {"id":"canada","name":"Canada","code":"CA"},
  {"id":"chile","name":"Chile","code":"CL"},
  {"id":"china","name":"China","code":"CN"},
  {"id":"colombia","name":"Colombia","code":"CO"},
  {"id":"costa-rica","name":"Costa Rica","code":"CR"},
  {"id":"croatia","name":"Croatia","code":"HR"},
  {"id":"cyprus","name":"Cyprus","code":"CY"},
  {"id":"czech-republic","name":"Czech Republic","code":"CZ"},
  {"id":"denmark","name":"Denmark","code":"DK"},
  {"id":"dominican-republic","name":"Dominican Republic","code":"DO"},
  {"id":"egypt","name":"Egypt","code":"EG"},
  {"id":"finland","name":"Finland","code":"FI"},
  {"id":"france","name":"France","code":"FR"},
  {"id":"germany","name":"Germany","code":"DE"},
  {"id":"greece","name":"Greece","code":"GR"},
  {"id":"guatemala","name":"Guatemala","code":"GT"},
  {"id":"haiti","name":"Haiti","code":"HT"},
  {"id":"hungary","name":"Hungary","code":"HU"},
  {"id":"india","name":"India","code":"IN"},
  {"id":"iraq","name":"Iraq","code":"IQ"},
  {"id":"ireland","name":"Ireland","code":"IE"},
  {"id":"israel","name":"Israel","code":"IL"},
  {"id":"italy","name":"Italy","code":"IT"},
  {"id":"japan","name":"Japan","code":"JP"},
  {"id":"jordan","name":"Jordan","code":"JO"},
  {"id":"kenya","name":"Kenya","code":"KE"},
  {"id":"kyrgyzstan","name":"Kyrgyzstan","code":"KG"},
  {"id":"latvia","name":"Latvia","code":"LV"},
  {"id":"luxembourg","name":"Luxembourg","code":"LU"},
  {"id":"malaysia","name":"Malaysia","code":"MY"},
  {"id":"mexico","name":"Mexico","code":"MX"},
  {"id":"nepal","name":"Nepal","code":"NP"},
  {"id":"netherlands","name":"Netherlands","code":"NL"},
  {"id":"new-zealand","name":"New Zealand","code":"NZ"},
  {"id":"nigeria","name":"Nigeria","code":"NG"},
  {"id":"norway","name":"Norway","code":"NO"},
  {"id":"Oman","name":"Oman","code":"OM"},
  {"id":"peru","name":"Peru","code":"PE"},
  {"id":"poland","name":"Poland","code":"PL"},
  {"id":"portugal","name":"Portugal","code":"PT"},
  {"id":"republic-of-korea","name":"Korea, Republic of","code":"KR"},
  {"id":"romania","name":"Romania","code":"RO"},
  {"id":"russia","name":"Russian Federation","code":"RU"},
  {"id":"suisse","name":"Switzerland","code":"CH"},
  {"id":"serbia","name":"Serbia","code":"RS"},
  {"id":"slovakia","name":"Slovakia","code":"SK"},
  {"id":"slovenia","name":"Slovenia","code":"SI"},
  {"id":"south-africa","name":"South Africa","code":"ZA"},
  {"id":"spain","name":"Spain","code":"ES"},
  {"id":"sweden","name":"Sweden","code":"SE"},
  {"id":"taiwan","name":"Taiwan, Province of China","code":"TW"},
  {"id":"tajikistan","name":"Tajikistan","code":"TJ"},
  {"id":"tanzania","name":"Tanzania, United Republic of","code":"TZ"},
  {"id":"thailand","name":"Thailand","code":"TH"},
  {"id":"turkey","name":"Turkey","code":"TR"},
  {"id":"uae","name":"United Arab Emirates","code":"AE"},
  {"id":"ukraine","name":"Ukraine","code":"UA"},
  {"id":"united-kingdom","name":"United Kingdom","code":"GB"},
  {"id":"usa","name":"United States","code":"US"},
  {"id":"vietnam","name":"Viet Nam","code":"VN"}
]}